
# Test your FastAPI endpoints

GET http://127.0.0.1:8004/health/
Accept: application/json

###

POST http://localhost:8004/robots/
Content-Type: application/json

{
  "kk_dict": {
    "kk_data": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8
    ],
    "kk_header": {
      "timestamp_sec": 1559752729,
      "robot_id": 232,
      "sys_type": "BBB"
    }
  }
}

###

GET http://localhost:8004/robots/1
Accept: application/json

###

GET http://localhost:8004/robots/robot_id/232/
Accept: application/json

### Get all robots

GET http://127.0.0.1:8004/robots/
Accept: application/json

###

DELETE http://127.0.0.1:8004/robots/20
Accept: application/json

###

DELETE http://127.0.0.1:8004/robots/robot_id/20
Accept: application/json

###


