apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-env
data:
  database_url: {{ .Values.database_url | b64enc }}
  client_id: {{ .Values.client_id | b64enc }}
  client_secret: {{ .Values.client_secret | b64enc }}